### ISSUE TITLE
Run errors

### ISSUE THREAD

**Issue by ganfeng2016** [msamribeiro/deep-cca#2]
python ./deep_cca.py
04/10/2021 15:57:52 INFO: ... loading data
04/10/2021 15:57:52 INFO: Downloading data from http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz
Traceback (most recent call last):
  File "./deep_cca.py", line 140, in <module>
    datasets = load_data(dataset, shared=True)
  File "/Users/ganfeng/BDYP/Python/deep-cca-master/data_provider.py", line 101, in load_data
    train_set = halve_dataset(train_set)
  File "/Users/ganfeng/BDYP/Python/deep-cca-master/data_provider.py", line 73, in halve_dataset
    left  = np.zeros((m, n/2))
TypeError: 'float' object cannot be interpreted as an integer

Could you tell me how to solve these errors?
cesgf at mail.sysu.edu.cn

**Comment by msamribeiro** [comment]
Please note that this is an old repository that is not longer updated. In fact, I don't think theano is even in development any more. If you're interested in Deep CCA, my advice would be to look for a recent PyTorch or Tensorflow implementation. Or take this as a guide and implement it yourself.

That being said, it seems like the issue here is n/2. Earlier version of Python were doing integer division, so n/2 would return a integer. Recent versions are doing true division, so n/2 will return a float. Doing int(n/2) should solve the problem, but it's likely you will find other issues after this one.
